services:
  app:
    build: .
    container_name: genealogie_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mongo
    networks:
      - app-network
    entrypoint: ["/bin/sh", "/var/www/html/import.sh"]
    secrets:
      - mongoMDP   # <-- monte le secret dans le conteneur app

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongoMDP
    secrets:
      - mongoMDP   # <-- monte le secret dans le conteneur mongo

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge

secrets:
  mongoMDP:
    file: ./secrets/mongoMDP.secret