services:
  app:
    image: fatymut/genealogie-app:v3
    container_name: genealogie_app
    ports:
      - "8080:80"
    depends_on:
      - mongo
    networks:
      - app-network
    volumes:
      - ./import.sh:/var/www/html/import.sh
    entrypoint: ["/bin/sh", "/var/www/html/import.sh"]
    secrets:
      - mongoMDP

  mongo:
    image: mongo:6
    container_name: genealogie_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongoMDP
    secrets:
      - mongoMDP

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge

secrets:
  mongoMDP:
    file: ./secrets/mongoMDP.secret
